/*
This file is part of Free Analysis and Interactive Reconstruction
for Structured Illumination Microscopy (fairSIM).

fairSIM is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

fairSIM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with fairSIM.  If not, see <http://www.gnu.org/licenses/>
*/

package org.fairsim.registration;

import java.awt.GridLayout;
import javax.swing.BorderFactory;
import org.fairsim.linalg.VectorFactory;
import org.fairsim.utils.Conf;

/**
 *
 * @author Mario
 */
public class RegistrationPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPanel
     */
    public RegistrationPanel(VectorFactory vf, Conf.Folder cfg, String[] channels) {
        initComponents();
        
        for (String channel : channels) {
            Registration.createRegistration(cfg, channel);
        }
        Registration.setWidefield(toggleWidefield.isSelected());
        Registration.setRecon(toggleRecon.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toggleWidefield = new javax.swing.JToggleButton();
        toggleRecon = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("image registration"));

        toggleWidefield.setText("register in widefield");
        toggleWidefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleWidefieldActionPerformed(evt);
            }
        });

        toggleRecon.setText("register in reconstruction");
        toggleRecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleReconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toggleWidefield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toggleRecon)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleWidefield)
                    .addComponent(toggleRecon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toggleWidefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleWidefieldActionPerformed
        Registration.setWidefield(toggleWidefield.isSelected());
    }//GEN-LAST:event_toggleWidefieldActionPerformed

    private void toggleReconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleReconActionPerformed
        Registration.setRecon(toggleRecon.isSelected());
    }//GEN-LAST:event_toggleReconActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton toggleRecon;
    private javax.swing.JToggleButton toggleWidefield;
    // End of variables declaration//GEN-END:variables
}
